language: go
go_import_path: github.com/elegos/flags
git:
  depth: 1
env:
  GO111MODULE=on
go: [1.11.x, 1.12.x, 1.13.x, 1.14.x]
os: [linux, osx]
install:
  - make deps
script:
  - make lint
  - make test
  - make coverage
after_success:
  - test $TRAVIS_BRANCH = "master" &&
    bash <(curl -s https://codecov.io/bash) -f out/coverage.profile
